version: "3.7"
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - /departi/sites/${DOMAIN}:/var/www/html
      - /departi/sites/wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini

    networks:
      - traefik_public
      - db_network
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      # WORDPRESS_DEBUG: 1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.wordpress_${SITE_NAME}.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.wordpress_${SITE_NAME}.entrypoints=websecure"
        - "traefik.http.routers.wordpress_${SITE_NAME}.tls.certresolver=le"
        - "traefik.http.routers.wordpress_${SITE_NAME}.service=wordpress_${SITE_NAME}"
        - "traefik.http.services.wordpress_${SITE_NAME}.loadbalancer.server.port=80"
        - "traefik.http.services.wordpress_${SITE_NAME}.loadbalancer.passHostHeader=true"

networks:
  traefik_public:
    external: true
  db_network:
    external: true